CREATE TABLE IF NOT EXISTS accounts (
  id VARCHAR(64) PRIMARY KEY,
  session_path VARCHAR(512) NOT NULL,
  is_logged_in TINYINT(1) NOT NULL DEFAULT 0,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account_id VARCHAR(64) NOT NULL,
  tiktok_username VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NULL,
  streak_days INT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  avatar_url VARCHAR(1024) NULL,
  last_parsed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_account_username (account_id, tiktok_username),
  CONSTRAINT fk_chats_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS send_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  chat_id INT NOT NULL,
  emoji VARCHAR(16) NOT NULL,
  status ENUM('success', 'error') NOT NULL,
  error TEXT NULL,
  sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_send_logs_chat FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS scheduler_state (
  account_id VARCHAR(64) PRIMARY KEY,
  next_run_at DATETIME NULL,
  last_run_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_scheduler_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
